### ISSUE TITLE
Challenging Domains in Registry

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryWebApp#24]
Within a domains profile, users will have the ability to challenge a domain's status. The amount of ADT needed to challenge will be established in the future. 

![image](https://user-images.githubusercontent.com/21111803/29689146-fb5e6c78-88d6-11e7-90d7-2b4b9e1b1500.png)

_The Wall Street Journal has been voted into the adChain Registry indefinitely based on the adToken accredidation as being non-fraudulent. If you believe that The Wall Street Journal is fraudulent and of low-quality, you are able to challenge it’s In Registry status below:_

_By Challenging, The Wall Street Journal will go into a series of voting phases where the general adToken community will determine its validity in the adChain Registry._

_If The Wall Street Journal has less than 10,000 ADT on-hand, they are automatically removed from the adChain Registry._

**Comment by miguelmota** [comment]
@eccheung4 see if you can test this
