### ISSUE TITLE
Master Refresh Button

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryWebApp#30]
Is there a way to refresh all domains' status?

![image](https://user-images.githubusercontent.com/21111803/30093409-fbdd3286-9279-11e7-8fe6-b5f13dab28b5.png)

All of these domains their application status already over. The user, at the moment, has to go through and refresh each of their statuses. 

- If one user refreshes the status and pays for the gas, does that update it for all users?
- Can there be a single button that refreshes all of the status, for the gas cost of one transaction?
@miguelmota @skmgoldin 

Please respond in the comments below.

**Comment by miguelmota** [comment]
@eduardo-munoz @skmgoldin is having passing an array of domains still feasible, or should we close this issue?

**Comment by skmgoldin** [comment]
It is _feasible_, but it's not elegant on the EVM side. I would vote for closing this.
