### ISSUE TITLE
Download Reminder

### ISSUE THREAD

**Issue by eduardo-munoz** [AdChain/AdChainRegistryWebApp#31]
Right next to the "Download Commit" button should be a "Download Reminder" where their calendar is synced with the beginning of the reveal phase. The reminder should be as follows:

Reveal [site.com] // adChain Registry
https://app.adchain.com/domains/site.com#! (this URL can be in the notes of the calendar reminder)

![image](https://user-images.githubusercontent.com/21111803/30093796-9f9fbd9c-927c-11e7-8588-54b3c04dad4f.png)

If possible, the calendar reminder can be simultaneously downloaded with the commit json file when the "Download Commit" button is pressed. For now, let's mandate the download of the json commit.

**Comment by miguelmota** [comment]
can use `ics` module for this https://github.com/adamgibbons/ics
